language: php
php:
- 7.4
before_script:
- composer install --dev
script:
- vendor/bin/phpunit -c phpunit.xml
before_deploy:
- composer install --no-dev
- make whalephant.phar
deploy:
  provider: releases
  api_key:
    secure: eVXZYsGyOdfBl99weR5jQ6VRMYAXKiOWfrVZ5s6FHKWmGTEK32ZMS3UzvQiIy1hwxhPHIIwU6RP0Tm7Lb93po/CLmJ7SK/1ifyvLL8MK33ytsM0agM+jG3yABVg7RxHxyEkVfe/AwDrEDTv8XSeom32Z/QD79WKx/bHEedV1i9uUXYCvQChBZYLePcfw0KAOslVkRfrJTTR4LZo5WW9mAhtiI7LMg3toZ8busNAvdA96kXYxQBq+t+lFtaE6tUBGNSl6dgHz+Q+U2GYQvRKBuZuwJc4Fy8+0fKKnThH82Zt6uI/9WZznNzYpTPck+48tau3sdo6zDNzrZjUqDYINPGlOHKIngr8ojuvfai2bS6SRRecPJabaImkyeYSBWHbAhQsCoqlG1gvmqWvPOzqRVAZzJpzGalh6xd/bxuAB/N7PPe1eakwc6lxifaoCYXycaTIAhPwb44XHU2uh4yYCUCHsWEw3+w/QE9bGFFDnEOBRpmZmtk6GfRAcpswpi8KF+7e8b5UR58/L2tMAVVKqDC6fQd/sOeJRG6+s+hyuIK8ngYy3tYpclW3uf47cWZpAzaNN4CCIgh8YyxeScd7idjhrRMLMq0+CgZM9dIN/4BdJ4qvrpUYZpD5LWCI1zy84mTQFPkn/p/tfSH/Ytyd1EjZ/tQwcVHgR8kf3azQvTR4=
  file: whalephant.phar
  on:
    repo: Niktux/whalephant
  skip_cleanup: 'true'
