#!/usr/bin/env php
<?php

use Whalephant\Application;
use Whalephant\Console;
use Puzzle\Configuration\Memory;

// Whalephant can be installed by phar or by composer (deprecated). Autoload.php is located differently in these cases
// Phar location needs to be tested first (__DIR__ is equals to phar://...)
$locations = [__DIR__ . '/vendor/autoload.php', __DIR__ . '/../../autoload.php'];
foreach($locations as $file)
{
    if(is_file($file))
    {
        require $file;
        break;
    }
}

$rootDir = __DIR__;

$configuration = new Memory([
	'app/id' => 'whalephant.phar',
	'app/var.path' => 'var', 
	'app/debug' => false,
	'twig/cache/directory' => false
]);

$app = new Application($configuration, $rootDir);

$console = new Console($app);
$console->run();
