on:
  push:
    tags: ['*']

name: whalephant.phar

jobs:
    build-whalephant:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v3

        - name: Install dependencies without dev requirements
          run: make composer-install-no-dev

        - name: Build whalephant.phar
          run: make whalephant.phar

        - name: Publish release
          uses: softprops/action-gh-release@v1
          with:
            files: whalephant.phar
            fail_on_unmatched_files: true
